"""This is a simple dictionary structure that presents a typical
:class:`geoutils.Metadata` object structure.

"""
i_3001a = {'file': 'i_3001a.ntf',
           'x_coord_size': '1024',
           'y_coord_size': '1024',
           'geogcs': 'GEOGCS["WGS 84",DATUM["WGS_1984",SPHEROID["WGS 84",6378137,298.257223563,AUTHORITY["EPSG","7030"]],TOWGS84[0,0,0,0,0,0,0],AUTHORITY["EPSG","6326"]],PRIMEM["Greenwich",0,AUTHORITY["EPSG","8901"]],UNIT["degree",0.0174532925199433,AUTHORITY["EPSG","9108"]],AUTHORITY["EPSG","4326"]]',
           'geoxform': [84.999999864233729, 2.7153252959988272e-07, 0.0, 32.983333469099598, 0.0, -2.7153252959294383e-07],
           'metadata': {'NITF_IDATIM': '19961217102630',
                        'NITF_FSCLAS': 'U',
                        'NITF_ISDGDT': '',
                        'NITF_FSCLTX': '',
                        'NITF_FSDGDT': '',
                        'NITF_ISDCDT': '',
                        'NITF_ENCRYP': '0',
                        'NITF_IC': 'NC',
                        'NITF_IID2': '- BASE IMAGE -',
                        'NITF_FSCATP': '',
                        'NITF_ABPP': '08',
                        'NITF_ILOC_ROW': '0',
                        'NITF_FBKGC': '255,255,255',
                        'NITF_FSREL': '',
                        'NITF_FSCAUT': '',
                        'NITF_ISCLSY': '',
                        'NITF_ISDCTP': '',
                        'NITF_STYPE': 'BF01',
                        'NITF_ISCTLH': '',
                        'NITF_FSCTLH': '',
                        'NITF_IMAG': '1.0 ',
                        'NITF_PJUST': 'R',
                        'NITF_ISREL': '',
                        'NITF_FSSRDT': '',
                        'NITF_ISCLAS': 'U',
                        'NITF_FHDR': 'NITF02.10',
                        'NITF_CLEVEL': '03',
                        'NITF_FDT': '19971217102630',
                        'NITF_ISCATP': '',
                        'NITF_ISCLTX': '',
                        'NITF_FSDCTP': '',
                        'NITF_ISCTLN': '',
                        'NITF_FSCLSY': '',
                        'NITF_FSCRSN': '',
                        'NITF_FSCTLN': '',
                        'NITF_FSDCDT': '',
                        'NITF_FTITLE': 'Checks an uncompressed 1024x1024 8 bit mono image with GEOcentric data. Airfield',
                        'NITF_FSDCXM': '',
                        'NITF_ISDCXM': '',
                        'NITF_IALVL': '0',
                        'NITF_IDLVL': '1',
                        'NITF_ONAME': 'JITC Fort Huachuca, AZ',
                        'NITF_ILOC_COLUMN': '0',
                        'NITF_ISCRSN': '',
                        'NITF_FSDG': '',
                        'NITF_TGTID': '',
                        'NITF_CCS_ROW': '0',
                        'NITF_ISDG': '',
                        'NITF_FSCPYS': '00000',
                        'NITF_ISORCE': 'Unknown',
                        'NITF_IMODE': 'B',
                        'NITF_OPHONE': '(520) 538-5458',
                        'NITF_FSCOP': '00000',
                        'NITF_CCS_COLUMN': '0',
                        'NITF_FSCODE': '',
                        'NITF_IID1': 'Missing ID',
                        'NITF_PVTYPE': 'INT',
                        'NITF_IREP': 'MONO',
                        'NITF_ISCODE': '',
                        'NITF_ISSRDT': '',
                        'NITF_ICAT': 'VIS',
                        'NITF_OSTAID': 'i_3001a',
                        'NITF_ISCAUT': ''}}
