"""This is a simple dictionary structure that presents a typical
:class:`geoutils.Metadata` object structure.

"""
DATA = {
    'row_id': 'i_3001a',
    'shard_id': 's01',
    'tables': {
        'meta_library': {
            'cf': {
                'cq': {
                    'coord=0': '32.9830554198,84.9999998642',
                    'coord=1': '32.9833334691,84.9999998642',
                    'coord=2': '32.9830554198,85.0002779135',
                    'coord=3': '32.9833334691,85.0002779135',
                    'file': 'i_3001a.ntf',
                    'x_coord_size': '1024',
                    'y_coord_size': '1024',
                    'geogcs': 'GEOGCS["WGS 84",DATUM["WGS_1984",SPHEROID["WGS 84",6378137,298.257223563,AUTHORITY["EPSG","7030"]],TOWGS84[0,0,0,0,0,0,0],AUTHORITY["EPSG","6326"]],PRIMEM["Greenwich",0,AUTHORITY["EPSG","8901"]],UNIT["degree",0.0174532925199433,AUTHORITY["EPSG","9108"]],AUTHORITY["EPSG","4326"]]',
                    'geoxform=0': '84.999999864233729',
                    'geoxform=1': '2.7153252959988272e-07',
                    'geoxform=2': '0.0',
                    'geoxform=3': '32.983333469099598',
                    'geoxform=4': '0.0',
                    'geoxform=5': '-2.7153252959294383e-07',
                    'metadata=NITF_IDATIM': '19961217102630',
                    'metadata=NITF_FSCLAS': 'U',
                    'metadata=NITF_ISDGDT': '',
                    'metadata=NITF_FSCLTX': '',
                    'metadata=NITF_FSDGDT': '',
                    'metadata=NITF_ISDCDT': '',
                    'metadata=NITF_ENCRYP': '0',
                    'metadata=NITF_IC': 'NC',
                    'metadata=NITF_IID2': '- BASE IMAGE -',
                    'metadata=NITF_FSCATP': '',
                    'metadata=NITF_ABPP': '08',
                    'metadata=NITF_ILOC_ROW': '0',
                    'metadata=NITF_FBKGC': '255,255,255',
                    'metadata=NITF_FSREL': '',
                    'metadata=NITF_FSCAUT': '',
                    'metadata=NITF_ISCLSY': '',
                    'metadata=NITF_ISDCTP': '',
                    'metadata=NITF_STYPE': 'BF01',
                    'metadata=NITF_ISCTLH': '',
                    'metadata=NITF_FSCTLH': '',
                    'metadata=NITF_IMAG': '1.0 ',
                    'metadata=NITF_PJUST': 'R',
                    'metadata=NITF_ISREL': '',
                    'metadata=NITF_FSSRDT': '',
                    'metadata=NITF_ISCLAS': 'U',
                    'metadata=NITF_FHDR': 'NITF02.10',
                    'metadata=NITF_CLEVEL': '03',
                    'metadata=NITF_FDT': '19971217102630',
                    'metadata=NITF_ISCATP': '',
                    'metadata=NITF_ISCLTX': '',
                    'metadata=NITF_FSDCTP': '',
                    'metadata=NITF_ISCTLN': '',
                    'metadata=NITF_FSCLSY': '',
                    'metadata=NITF_FSCRSN': '',
                    'metadata=NITF_FSCTLN': '',
                    'metadata=NITF_FSDCDT': '',
                    'metadata=NITF_FTITLE': 'Checks an uncompressed 1024x1024 8 bit mono image with GEOcentric data. Airfield',
                    'metadata=NITF_FSDCXM': '',
                    'metadata=NITF_ISDCXM': '',
                    'metadata=NITF_IALVL': '0',
                    'metadata=NITF_IDLVL': '1',
                    'metadata=NITF_ONAME': 'JITC Fort Huachuca, AZ',
                    'metadata=NITF_ILOC_COLUMN': '0',
                    'metadata=NITF_ISCRSN': '',
                    'metadata=NITF_FSDG': '',
                    'metadata=NITF_TGTID': '',
                    'metadata=NITF_CCS_ROW': '0',
                    'metadata=NITF_ISDG': '',
                    'metadata=NITF_FSCPYS': '00000',
                    'metadata=NITF_ISORCE': 'Unknown',
                    'metadata=NITF_IMODE': 'B',
                    'metadata=NITF_OPHONE': '(520) 538-5458',
                    'metadata=NITF_FSCOP': '00000',
                    'metadata=NITF_CCS_COLUMN': '0',
                    'metadata=NITF_FSCODE': '',
                    'metadata=NITF_IID1': 'Missing ID',
                    'metadata=NITF_PVTYPE': 'INT',
                    'metadata=NITF_IREP': 'MONO',
                    'metadata=NITF_ISCODE': '',
                    'metadata=NITF_ISSRDT': '',
                    'metadata=NITF_ICAT': 'VIS',
                    'metadata=NITF_OSTAID': 'i_3001a',
                    'metadata=NITF_ISCAUT': '',
                },
            },
        },
    },
}
