"""This is a simple dictionary structure that presents a typical
:class:`geoutils.Metadata` object structure.

..note::

    Data sample features a missing GEOGCS (Geographic Coordinate System)

"""
DATA = {
    'row_id': 'i_6130e',
    'tables': {
        'meta_test': {
            'cf': {
                'cq': {
                    'file': 'i_6130e.ntf',
                    'x_coord_size': '1152',
                    'y_coord_size': '1280',
                    'geogcs': '',
                    'geoxform=0': '0.0',
                    'geoxform=1': '1.0',
                    'geoxform=2': '0.0',
                    'geoxform=3': '0.0',
                    'geoxform=4': '0.0',
                    'geoxform=5': '1.0',
                    'metadata=NITF_IDATIM': '--------------',
                    'metadata=NITF_FSCLAS': 'U',
                    'metadata=NITF_ISDGDT': '',
                    'metadata=NITF_FSCLTX': '',
                    'metadata=NITF_FSDGDT': '',
                    'metadata=NITF_ISDCDT': '',
                    'metadata=NITF_ENCRYP': '0',
                    'metadata=NITF_IC': 'NC',
                    'metadata=NITF_IID2': '',
                    'metadata=NITF_FSCATP': '',
                    'metadata=NITF_ABPP': '08',
                    'metadata=NITF_ILOC_ROW': '0',
                    'metadata=NITF_FBKGC': '  0,127,  0',
                    'metadata=NITF_FSREL': '',
                    'metadata=NITF_FSCAUT': '',
                    'metadata=NITF_ISCLSY': '',
                    'metadata=NITF_ISDCTP': '',
                    'metadata=NITF_STYPE': 'BF01',
                    'metadata=NITF_ISCTLH': '',
                    'metadata=NITF_FSCTLH': '',
                    'metadata=NITF_IMAG': '1.0 ',
                    'metadata=NITF_PJUST': 'R',
                    'metadata=NITF_ISREL': '',
                    'metadata=NITF_FSSRDT': '',
                    'metadata=NITF_ISCLAS': 'U',
                    'metadata=NITF_FHDR': 'NITF02.10',
                    'metadata=NITF_CLEVEL': '03',
                    'metadata=NITF_FDT': '20140804061730',
                    'metadata=NITF_ISCATP': '',
                    'metadata=NITF_ISCLTX': '',
                    'metadata=NITF_FSDCTP': '',
                    'metadata=NITF_ISCTLN': '',
                    'metadata=NITF_FSCLSY': '',
                    'metadata=NITF_FSCRSN': '',
                    'metadata=NITF_FSCTLN': '',
                    'metadata=NITF_FSDCDT': '',
                    'metadata=NITF_FTITLE': 'i_6130e.ntf_8.wrk',
                    'metadata=NITF_FSDCXM': '',
                    'metadata=NITF_ISDCXM': '',
                    'metadata=NITF_IALVL': '0',
                    'metadata=NITF_IDLVL': '1',
                    'metadata=NITF_ONAME': '',
                    'metadata=NITF_ILOC_COLUMN': '0',
                    'metadata=NITF_ISCRSN': '',
                    'metadata=NITF_FSDG': '',
                    'metadata=NITF_TGTID': '',
                    'metadata=NITF_CCS_ROW': '0',
                    'metadata=NITF_ISDG': '',
                    'metadata=NITF_FSCPYS': '00000',
                    'metadata=NITF_ISORCE': '',
                    'metadata=NITF_IMODE': 'B',
                    'metadata=NITF_OPHONE': '',
                    'metadata=NITF_FSCOP': '00000',
                    'metadata=NITF_CCS_COLUMN': '0',
                    'metadata=NITF_FSCODE': '',
                    'metadata=NITF_IID1': 'Missing ID',
                    'metadata=NITF_PVTYPE': 'INT',
                    'metadata=NITF_IREP': 'MONO',
                    'metadata=NITF_ISCODE': '',
                    'metadata=NITF_ISSRDT': '',
                    'metadata=NITF_ICAT': 'VIS',
                    'metadata=NITF_OSTAID': '',
                    'metadata=NITF_ISCAUT': '',
                },
            },
        },
    },
}
