from test_metadata import TestModelMetadata
from test_metasearch import TestModelMetasearch
from test_image import TestModelImage
from test_thumb import TestModelThumb
from test_spatial import TestModelSpatial
